### PR TITLE
Add MasterPassword paramater

### PR DESCRIPTION
**Pull request by lim3ra**
MasterPassword paramater added so you can establish connection without user prompt. Useful for Powershell automation scripts where you cannot prompt the value.

### CODE REVIEW

**Comment by sk-keeper** [comment]
> MasterPassword paramater added so you can establish connection without user prompt. Useful for Powershell automation scripts where you cannot prompt the value.

Do you have SSO account and want to login with a password? 
`Connect-Keeper` has `SsoPassword` that forces password flow for SSO accounts.
```
$password='<Password>'
Connect-Keeper -Password=$password -SsoPassword <account_email>
```

**Comment by lim3ra** [comment]
> > MasterPassword paramater added so you can establish connection without user prompt. Useful for Powershell automation scripts where you cannot prompt the value.
> 
> 
> 
> Do you have SSO account and want to login with a password? 
> 
> `Connect-Keeper` has `SsoPassword` parameter that forces master password flow for SSO accounts.
> 
> ```
> 
> $password='<Password>'
> 
> Connect-Keeper -Password=$password -SsoPassword <account_email>
> 
> ```
> 
> 
> 
> 
> 
> 

Hi, yes it has.

But when you put -SsoPassword, it will generate you a Write-Host prompt so you can write your password and accept with "Enter". (See that -SsoPassword is type "switch")

In my case I need to have fully automated solution, and I would like to pass MasterPassword as a variable without user interaction.

**Comment by sk-keeper** [comment]
It is a bug if `-SsoPassword` parameter does not work with `-Password` one for SSO accounts.
It will be fixed soon.

**Comment by lim3ra** [comment]
> It is a bug if `-SsoPassword` parameter does not work with `-Password` one for SSO accounts. It will be fixed soon.

It's not a bug, please see line 338 in PowerCommander/AuthCommands.ps1:

`[Parameter(ParameterSetName = 'sso_password')][switch] $SsoPassword,`

when you run: kc -Username $username -Password $pass -SsoPassword it will trigger ask user to choose between SSO token and master password, then it will trigger Write-Host command at some point and it will wait for user interaction to type master password in the popup window.

When you want to use this tool in automation, you cannot have Write-Window because you won't be able to type password manually, you have to pass the password as variable. In current version of the module you cannot do something like that:

kc -Username $username -Password $pass -SsoPassword $masterpassword <- that line won't work because -SsoPassword can be only true or false

That's why new parameter is needed (to keep backward compatibility) for example -MasterPassword so you can pass variable to it and connect without additional manual prompt:
kc -Username $username -Password $pass -MasterPassword $masterpassword

**Comment by sk-keeper** [comment]
`-SsoPassword` is a switch/flag that starts password flow for SSO accounts.
There should not be any option between SSO and password logins.
If the app shows prompt it is a bug

**Comment by sk-keeper** [comment]
The latest version works as expected.
```
$password= Read-Host -AsSecureString ...
Connect-Keeper -Password=$password -SsoPassword <account_email>
```
does not show any input.

**Comment by lim3ra** [comment]
Ok, I can confirm 

`kc -Password $masterpassword -SsoPassword $username` works if you want to connect using master password

It would be great if we could mention that in the official powershell docs for this module.

Thank you for your help, @sk-keeper !

**Pull request closed without merging**
